# Generated by Django 2.2.8 on 2019-12-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd')], max_length=10)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.Processor')),
            ],
        ),
    ]
