# Generated by Django 2.2.8 on 2019-12-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20191215_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='processor',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.GraphicsCard')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.Memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.MotherBoard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.Processor')),
            ],
        ),
    ]
