# Generated by Django 2.2.8 on 2019-12-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_auto_20191215_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='memory',
        ),
        migrations.AddField(
            model_name='order',
            name='memory',
            field=models.ManyToManyField(to='computers.Memory'),
        ),
    ]
