# Generated by Django 2.2.8 on 2020-01-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_auto_20191215_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'Memories'},
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='brand',
        ),
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.Brand'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='brand',
            field=models.ManyToManyField(to='computers.Brand'),
        ),
    ]
